version: '3.1'
services:
  db:
    image: mysql:8.4.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: TBL_Project2024
      MYSQL_USER: tbl_user
      MYSQL_PASSWORD: TBL_Project2024
      MYSQL_DATABASE: tbl_demo
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

